### ISSUE TITLE
Alerta No Send Resolve

### ISSUE THREAD

**Issue by vinfry** [prometheus/alertmanager#4251]
Good day,

I have started to face weird issues after upgrading Alertmanager to the latest version:

0.28.0

I have a lot of alert rules and different receivers, the one which is in problem is alerta. The "resolve" message is not sent to Alerta and the alert appears in Alerta until I delete it. I could not track why this is happening and the most amazing thing is that it happens at random times.
Here is receiver config in /etc/alertmanager/alertmanager.yml :

- name: 'alerta'
  webhook_configs:
  - url: 'http://$alerta_host:8080/webhooks/prometheus?api-key=$KEY'
    send_resolved: true

Debug logs of successful sending of the same alert id:
```
Feb 08 20:21:49 $host alertmanager[1325]: time=2025-02-08T18:21:49.027Z level=DEBUG source=notify.go:876 msg="Notify success" component=dispatcher receiver=receiver integration=email[1] $redacted attempts=1 duration=49.21519ms alerts=[$alertname[d560a81][active]]
Feb 08 20:21:49 $host alertmanager[1325]: time=2025-02-08T18:21:49.027Z level=DEBUG source=notify.go:876 msg="Notify success" component=dispatcher receiver=receiver integration=email[0] $redacted attempts=1 duration=49.184398ms alerts=[$alertname[d560a81][active]]
Feb 08 20:21:49 $host alertmanager[1325]: time=2025-02-08T18:21:49.051Z level=DEBUG source=notify.go:876 msg="Notify success" component=dispatcher receiver=alerta integration=webhook[0] $redacted attempts=1 duration=72.965561ms alerts=[$alertname[d560a81][active]]

some debug logs...

Feb 08 20:26:49 $host alertmanager[1325]: time=2025-02-08T18:26:49.006Z level=DEBUG source=notify.go:876 msg="Notify success" component=dispatcher receiver=receiver integration=email[0] $redacted attempts=1 duration=21.456558ms alerts=[$alertname[d560a81][resolved]]
Feb 08 20:26:49 $host alertmanager[1325]: time=2025-02-08T18:26:49.017Z level=DEBUG source=notify.go:876 msg="Notify success" component=dispatcher receiver=MW-VFU-MYVODAFONE integration=email[1] $redacted attempts=1 duration=32.341313ms alerts=[$alertname[d560a81][resolved]]
Feb 08 20:26:49 $host alertmanager[1325]: time=2025-02-08T18:26:49.160Z level=DEBUG source=notify.go:876 msg="Notify success" component=dispatcher receiver=alerta integration=webhook[0] $redacted attempts=1 duration=175.729277ms alerts=[$alertname[d560a81][resolved]]
```

The next one failed to send "resolve":

```
Feb 10 15:58:19 $host alertmanager[1325]: time=2025-02-10T13:58:19.005Z level=DEBUG source=notify.go:876 msg="Notify success" component=dispatcher receiver=$receiver integration=email[0] $redacted attempts=1 duration=15.78611ms alerts=[$alertname[d560a81][active]]
Feb 10 15:58:19 $host alertmanager[1325]: time=2025-02-10T13:58:19.007Z level=DEBUG source=notify.go:876 msg="Notify success" component=dispatcher receiver=$receiver integration=email[1] $redacted attempts=1 duration=17.254232ms alerts=[$alertname[d560a81][active]]
Feb 10 15:58:19 $host alertmanager[1325]: time=2025-02-10T13:58:19.038Z level=DEBUG source=notify.go:876 msg="Notify success" component=dispatcher receiver=alerta integration=webhook[0] $redacted attempts=1 duration=48.615119ms alerts=[$alertname[d560a81][active]]

some debug logs...

Feb 10 16:03:19 $host alertmanager[1325]: time=2025-02-10T14:03:19.009Z level=DEBUG source=notify.go:876 msg="Notify success" component=dispatcher receiver=$receiver integration=email[0] $redacted attempts=1 duration=18.54338ms alerts=[$alertname[d560a81][resolved]]
Feb 10 16:03:19 $host alertmanager[1325]: time=2025-02-10T14:03:19.010Z level=DEBUG source=notify.go:876 msg="Notify success" component=dispatcher receiver=$receiver integration=email[1] $redacted attempts=1 duration=20.019582ms alerts=[$alertname[d560a81][resolved]]
Feb 10 16:03:49 $host alertmanager[1325]: time=2025-02-10T14:03:49.098Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alertname[d560a81][resolved]

```

I have debugged a few cases and found nothing that could help. No errors, nothing in TCP traces about rejected connections or similar.
As for Alertmanager itself, those alerts disappear without any problems.
If you need some additional info please let me know.

**Comment by grobinson-grafana** [comment]
It looks like you have a `group_interval` of `5s`, is that correct? Based on the logs, I am guessing that the webhook took longer than 5 seconds and was canceled 5 seconds later. You should be able to find an error message like `notify retry canceled` or `context deadline exceeded`.

**Comment by vinfry** [comment]
> It looks like you have a `group_interval` of `5s`, is that correct? Based on the logs, I am guessing that the webhook took longer than 5 seconds and was canceled 5 seconds later. You should be able to find an error message like `notify retry canceled` or `context deadline exceeded`.
Here is:
group_interval: 5m
and I see nothing in debug logs like "notify retry canceled" or "context deadline exceeded".

**Comment by vinfry** [comment]
```
Feb 10 15:57:48 $host alertmanager[1325]: time=2025-02-10T13:57:48.988Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alertname[d560a81][active]
Feb 10 15:57:49 $host alertmanager[1325]: time=2025-02-10T13:57:49.018Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alertname[d560a81][active]
Feb 10 15:58:18 $host alertmanager[1325]: time=2025-02-10T13:58:18.989Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher aggrGroup="$alert alerts=[$alertname[d560a81][active]]
Feb 10 15:58:18 $host alertmanager[1325]: time=2025-02-10T13:58:18.989Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher aggrGroup="$alert alerts=[$alertname[d560a81][active]]
Feb 10 15:58:19 $host alertmanager[1325]: time=2025-02-10T13:58:19.005Z level=DEBUG source=notify.go:876 msg="Notify success" component=dispatcher receiver=$email integration=email[0] aggrGroup="$alert attempts=1 duration=15.78611ms alerts=[$alertname[d560a81][active]]
Feb 10 15:58:19 $host alertmanager[1325]: time=2025-02-10T13:58:19.007Z level=DEBUG source=notify.go:876 msg="Notify success" component=dispatcher receiver=$email integration=email[1] aggrGroup="$alert attempts=1 duration=17.254232ms alerts=[$alertname[d560a81][active]]
Feb 10 15:58:19 $host alertmanager[1325]: time=2025-02-10T13:58:19.038Z level=DEBUG source=notify.go:876 msg="Notify success" component=dispatcher receiver=nm-alerta integration=webhook[0] aggrGroup="$alert attempts=1 duration=48.615119ms alerts=[$alertname[d560a81][active]]
Feb 10 15:59:19 $host alertmanager[1325]: time=2025-02-10T13:59:19.117Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alertname[d560a81][active]
Feb 10 15:59:19 $host alertmanager[1325]: time=2025-02-10T13:59:19.141Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alertname[d560a81][active]
Feb 10 16:00:49 $host alertmanager[1325]: time=2025-02-10T14:00:49.196Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alertname[d560a81][active]
Feb 10 16:00:49 $host alertmanager[1325]: time=2025-02-10T14:00:49.196Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alertname[d560a81][active]
Feb 10 16:02:18 $host alertmanager[1325]: time=2025-02-10T14:02:18.932Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alertname[d560a81][resolved]
Feb 10 16:02:18 $host alertmanager[1325]: time=2025-02-10T14:02:18.945Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alertname[d560a81][resolved]
Feb 10 16:03:18 $host alertmanager[1325]: time=2025-02-10T14:03:18.990Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher aggrGroup="$alert alerts=[$alertname[d560a81][resolved]]
Feb 10 16:03:18 $host alertmanager[1325]: time=2025-02-10T14:03:18.990Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher aggrGroup="$alert alerts=[$alertname[d560a81][resolved]]
Feb 10 16:03:19 $host alertmanager[1325]: time=2025-02-10T14:03:19.009Z level=DEBUG source=notify.go:876 msg="Notify success" component=dispatcher receiver=$email integration=email[0] aggrGroup="$alert attempts=1 duration=18.54338ms alerts=[$alertname[d560a81][resolved]]
Feb 10 16:03:19 $host alertmanager[1325]: time=2025-02-10T14:03:19.010Z level=DEBUG source=notify.go:876 msg="Notify success" component=dispatcher receiver=$email integration=email[1] aggrGroup="$alert attempts=1 duration=20.019582ms alerts=[$alertname[d560a81][resolved]]
Feb 10 16:03:49 $host alertmanager[1325]: time=2025-02-10T14:03:49.098Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alertname[d560a81][resolved]
Feb 10 16:03:49 $host alertmanager[1325]: time=2025-02-10T14:03:49.098Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher aggrGroup="$alert alerts=[$alertname[d560a81][resolved]]
Feb 10 16:03:49 $host alertmanager[1325]: time=2025-02-10T14:03:49.098Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher aggrGroup="$alert alerts=[$alertname[d560a81][resolved]]
Feb 10 16:03:49 $host alertmanager[1325]: time=2025-02-10T14:03:49.101Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alertname[d560a81][resolved]
Feb 10 16:05:19 $host alertmanager[1325]: time=2025-02-10T14:05:19.125Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alertname[d560a81][resolved]
Feb 10 16:05:19 $host alertmanager[1325]: time=2025-02-10T14:05:19.138Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alertname[d560a81][resolved]
Feb 10 16:06:49 $host alertmanager[1325]: time=2025-02-10T14:06:49.145Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alertname[d560a81][resolved]
Feb 10 16:06:49 $host alertmanager[1325]: time=2025-02-10T14:06:49.232Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alertname[d560a81][resolved]
Feb 10 16:08:18 $host alertmanager[1325]: time=2025-02-10T14:08:18.939Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alertname[d560a81][resolved]
Feb 10 16:08:18 $host alertmanager[1325]: time=2025-02-10T14:08:18.950Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alertname[d560a81][resolved]
Feb 10 16:08:49 $host alertmanager[1325]: time=2025-02-10T14:08:49.099Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher aggrGroup="$alert alerts=[$alertname[d560a81][resolved]]
Feb 10 16:08:49 $host alertmanager[1325]: time=2025-02-10T14:08:49.101Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher aggrGroup="$alert alerts=[$alertname[d560a81][resolved]]
Feb 10 16:09:49 $host alertmanager[1325]: time=2025-02-10T14:09:49.033Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alertname[d560a81][resolved]
Feb 10 16:09:49 $host alertmanager[1325]: time=2025-02-10T14:09:49.037Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher aggrGroup="$alert alerts=[$alertname[d560a81][resolved]]
Feb 10 16:09:49 $host alertmanager[1325]: time=2025-02-10T14:09:49.037Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher aggrGroup="$alert alerts=[$alertname[d560a81][resolved]]
Feb 10 16:09:49 $host alertmanager[1325]: time=2025-02-10T14:09:49.063Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alertname[d560a81][resolved]
Feb 10 16:11:19 $host alertmanager[1325]: time=2025-02-10T14:11:19.027Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alertname[d560a81][resolved]
Feb 10 16:11:19 $host alertmanager[1325]: time=2025-02-10T14:11:19.050Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alertname[d560a81][resolved]
Feb 10 16:12:49 $host alertmanager[1325]: time=2025-02-10T14:12:49.225Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alertname[d560a81][resolved]
Feb 10 16:12:49 $host alertmanager[1325]: time=2025-02-10T14:12:49.225Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alertname[d560a81][resolved]
Feb 10 16:14:19 $host alertmanager[1325]: time=2025-02-10T14:14:19.145Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alertname[d560a81][resolved]
Feb 10 16:14:19 $host alertmanager[1325]: time=2025-02-10T14:14:19.204Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alertname[d560a81][resolved]
Feb 10 16:14:49 $host alertmanager[1325]: time=2025-02-10T14:14:49.037Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher aggrGroup="$alert alerts=[$alertname[d560a81][resolved]]
Feb 10 16:14:49 $host alertmanager[1325]: time=2025-02-10T14:14:49.038Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher aggrGroup="$alert alerts=[$alertname[d560a81][resolved]]
Feb 10 16:15:48 $host alertmanager[1325]: time=2025-02-10T14:15:48.961Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alertname[d560a81][resolved]
Feb 10 16:15:48 $host alertmanager[1325]: time=2025-02-10T14:15:48.961Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher aggrGroup="$alert alerts=[$alertname[d560a81][resolved]]
Feb 10 16:15:48 $host alertmanager[1325]: time=2025-02-10T14:15:48.961Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher aggrGroup="$alert alerts=[$alertname[d560a81][resolved]]
Feb 10 16:15:48 $host alertmanager[1325]: time=2025-02-10T14:15:48.977Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alertname[d560a81][resolved]
Feb 10 16:17:18 $host alertmanager[1325]: time=2025-02-10T14:17:18.954Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alertname[d560a81][resolved]
Feb 10 16:17:18 $host alertmanager[1325]: time=2025-02-10T14:17:18.959Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alertname[d560a81][resolved]
Feb 10 16:20:48 $host alertmanager[1325]: time=2025-02-10T14:20:48.962Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher aggrGroup="$alert alerts=[$alertname[d560a81][resolved]]
Feb 10 16:20:48 $host alertmanager[1325]: time=2025-02-10T14:20:48.962Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher aggrGroup="$alert alerts=[$alertname[d560a81][resolved]]
```

Full log for d560a81 id using grep

**Comment by grobinson-grafana** [comment]
There are two groups here, but have both been redacted to `$alert`. I assume these are different routes? Can you make them unique so I can see which notification is for which group? Just `$group1` and `$group2` would be sufficient.

```
Feb 10 15:58:18 $host alertmanager[1325]: time=2025-02-10T13:58:18.989Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher aggrGroup="$alert alerts=[$alertname[d560a81][active]]
Feb 10 15:58:18 $host alertmanager[1325]: time=2025-02-10T13:58:18.989Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher aggrGroup="$alert alerts=[$alertname[d560a81][active]]
``

**Comment by grobinson-grafana** [comment]
Here is a test I did, and this is what I would have expected to see if the webhook timed out:

```
time=2025-02-14T12:47:57.041Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher aggrGroup={}:{} alerts=[[3fff2c2][active]]
time=2025-02-14T12:52:57.040Z level=ERROR source=dispatch.go:360 msg="Notify for alerts failed" component=dispatcher num_alerts=1 err="test1/webhook[0]: notify retry canceled after 2 attempts: context deadline exceeded"
time=2025-02-14T12:52:57.040Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher aggrGroup={}:{} alerts=[[3fff2c2][active]]
```

It's odd that you did not have a similar error, as I would have expected either a `Notify success` or `Notify for alerts failed` message.

**Comment by vinfry** [comment]
I have just searched alertmanager log for 'level=ERROR' but found nothing.
systemctl settings:
`ExecStart=/usr/local/bin/alertmanager \
        --config.file="/etc/alertmanager/alertmanager.yml" \
        --storage.path="/var/lib/alertmanager" \
        --cluster.listen-address="0.0.0.0:9094" \
        --cluster.peer="$instance2:9094" \
        --log.level=debug`
Note: pay attention to cluster.peer, i browsed its logs as well.
I might have to put something additional to see level=ERROR in addition to "debug"?
Also, I have a newer example:
```
Feb 17 13:27:09 $host alertmanager[1325]: time=2025-02-17T11:27:09.769Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alert_name[4c9d39e][active]
Feb 17 13:27:09 $host alertmanager[1325]: time=2025-02-17T11:27:09.777Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alert_name[4c9d39e][active]
Feb 17 13:27:39 $host alertmanager[1325]: time=2025-02-17T11:27:39.770Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher $alert alerts=[$alert_name[4c9d39e][active]]
Feb 17 13:27:39 $host alertmanager[1325]: time=2025-02-17T11:27:39.770Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher $alert alerts=[$alert_name[4c9d39e][active]]
Feb 17 13:27:39 $host alertmanager[1325]: time=2025-02-17T11:27:39.795Z level=DEBUG source=notify.go:876 msg="Notify success" component=dispatcher receiver=$receiver integration=email[1] $alert attempts=1 duration=24.61405ms alerts=[$alert_name[4c9d39e][active]]
Feb 17 13:27:39 $host alertmanager[1325]: time=2025-02-17T11:27:39.797Z level=DEBUG source=notify.go:876 msg="Notify success" component=dispatcher receiver=$receiver integration=email[0] $alert attempts=1 duration=26.48321ms alerts=[$alert_name[4c9d39e][active]]
Feb 17 13:27:39 $host alertmanager[1325]: time=2025-02-17T11:27:39.799Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alert_name[4c9d39e][resolved]
Feb 17 13:27:39 $host alertmanager[1325]: time=2025-02-17T11:27:39.826Z level=DEBUG source=notify.go:876 msg="Notify success" component=dispatcher receiver=alerta integration=webhook[0] $alert attempts=1 duration=55.562792ms alerts=[$alert_name[4c9d39e][active]]
Feb 17 13:27:39 $host alertmanager[1325]: time=2025-02-17T11:27:39.835Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alert_name[4c9d39e][resolved]
Feb 17 13:29:09 $host alertmanager[1325]: time=2025-02-17T11:29:09.758Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alert_name[4c9d39e][resolved]
Feb 17 13:29:09 $host alertmanager[1325]: time=2025-02-17T11:29:09.758Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alert_name[4c9d39e][resolved]
Feb 17 13:30:39 $host alertmanager[1325]: time=2025-02-17T11:30:39.776Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alert_name[4c9d39e][resolved]
Feb 17 13:30:39 $host alertmanager[1325]: time=2025-02-17T11:30:39.778Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alert_name[4c9d39e][resolved]
Feb 17 13:32:09 $host alertmanager[1325]: time=2025-02-17T11:32:09.774Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alert_name[4c9d39e][resolved]
Feb 17 13:32:09 $host alertmanager[1325]: time=2025-02-17T11:32:09.793Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alert_name[4c9d39e][resolved]
Feb 17 13:32:39 $host alertmanager[1325]: time=2025-02-17T11:32:39.771Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher $alert alerts=[$alert_name[4c9d39e][resolved]]
Feb 17 13:32:39 $host alertmanager[1325]: time=2025-02-17T11:32:39.771Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher $alert alerts=[$alert_name[4c9d39e][resolved]]
Feb 17 13:32:39 $host alertmanager[1325]: time=2025-02-17T11:32:39.794Z level=DEBUG source=notify.go:876 msg="Notify success" component=dispatcher receiver=$receiver integration=email[1] $alert attempts=1 duration=22.808079ms alerts=[$alert_name[4c9d39e][resolved]]
Feb 17 13:32:39 $host alertmanager[1325]: time=2025-02-17T11:32:39.813Z level=DEBUG source=notify.go:876 msg="Notify success" component=dispatcher receiver=$receiver integration=email[0] $alert attempts=1 duration=41.195493ms alerts=[$alert_name[4c9d39e][resolved]]
Feb 17 13:33:39 $host alertmanager[1325]: time=2025-02-17T11:33:39.834Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alert_name[4c9d39e][resolved]
Feb 17 13:33:39 $host alertmanager[1325]: time=2025-02-17T11:33:39.834Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher $alert alerts=[$alert_name[4c9d39e][resolved]]
Feb 17 13:33:39 $host alertmanager[1325]: time=2025-02-17T11:33:39.834Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher $alert alerts=[$alert_name[4c9d39e][resolved]]
Feb 17 13:33:39 $host alertmanager[1325]: time=2025-02-17T11:33:39.835Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alert_name[4c9d39e][resolved]
Feb 17 13:35:09 $host alertmanager[1325]: time=2025-02-17T11:35:09.754Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alert_name[4c9d39e][resolved]
Feb 17 13:35:09 $host alertmanager[1325]: time=2025-02-17T11:35:09.762Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alert_name[4c9d39e][resolved]
Feb 17 13:36:39 $host alertmanager[1325]: time=2025-02-17T11:36:39.771Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alert_name[4c9d39e][resolved]
Feb 17 13:36:39 $host alertmanager[1325]: time=2025-02-17T11:36:39.780Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alert_name[4c9d39e][resolved]
Feb 17 13:38:09 $host alertmanager[1325]: time=2025-02-17T11:38:09.749Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alert_name[4c9d39e][resolved]
Feb 17 13:38:09 $host alertmanager[1325]: time=2025-02-17T11:38:09.749Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alert_name[4c9d39e][resolved]
Feb 17 13:38:39 $host alertmanager[1325]: time=2025-02-17T11:38:39.835Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher $alert alerts=[$alert_name[4c9d39e][resolved]]
Feb 17 13:38:39 $host alertmanager[1325]: time=2025-02-17T11:38:39.838Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher $alert alerts=[$alert_name[4c9d39e][resolved]]
Feb 17 13:39:39 $host alertmanager[1325]: time=2025-02-17T11:39:39.810Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alert_name[4c9d39e][resolved]
Feb 17 13:39:39 $host alertmanager[1325]: time=2025-02-17T11:39:39.810Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher $alert alerts=[$alert_name[4c9d39e][resolved]]
Feb 17 13:39:39 $host alertmanager[1325]: time=2025-02-17T11:39:39.810Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher $alert alerts=[$alert_name[4c9d39e][resolved]]
Feb 17 13:39:39 $host alertmanager[1325]: time=2025-02-17T11:39:39.849Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alert_name[4c9d39e][resolved]
Feb 17 13:41:09 $host alertmanager[1325]: time=2025-02-17T11:41:09.820Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alert_name[4c9d39e][resolved]
Feb 17 13:41:09 $host alertmanager[1325]: time=2025-02-17T11:41:09.885Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alert_name[4c9d39e][resolved]
Feb 17 13:42:39 $host alertmanager[1325]: time=2025-02-17T11:42:39.776Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alert_name[4c9d39e][resolved]
Feb 17 13:42:39 $host alertmanager[1325]: time=2025-02-17T11:42:39.787Z level=DEBUG source=dispatch.go:165 msg="Received alert" component=dispatcher alert=$alert_name[4c9d39e][resolved]
Feb 17 13:44:39 $host alertmanager[1325]: time=2025-02-17T11:44:39.816Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher $alert alerts=[$alert_name[4c9d39e][resolved]]
Feb 17 13:44:39 $host alertmanager[1325]: time=2025-02-17T11:44:39.816Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher $alert alerts=[$alert_name[4c9d39e][resolved]]
```
As for receivers, I made some modifications to the redaction:)
Just in case, here is the receiver config:
```
- name: "$receiver"
  email_configs:
  - to: '$email1'
    send_resolved: true
  - to: '$email2'
    send_resolved: true
```

**Comment by grobinson-grafana** [comment]
The obfuscation of information makes it so difficult to help. I asked if you could at least make the redacted Group Key unique so I can differentiate between the two groups, but you haven't done this so I can't tell which group (I believe there are two) is for which `msg=flushing`, or the associated notifications.

Also, the receiver configuration you share doesn't even have an entry for your Alerta webhook?

**Comment by vinfry** [comment]
sorry for this, however, the group is the same, the only difference is email, this group has 2 different emails to send notifications to:
`integration=email[0]` and `integration=email[1]`
I have shared the info about alerta webhook in the 1st post, here it is again:

name: 'alerta'
webhook_configs:
url: 'http://$alerta_host:8080/webhooks/prometheus?api-key=$KEY'
send_resolved: true

**Comment by grobinson-grafana** [comment]
That doesn't seem possible. The logs suggest to me that you have two groups, as shown here:

```

Feb 17 13:32:39 $host alertmanager[1325]: time=2025-02-17T11:32:39.771Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher $alert alerts=[$alert_name[4c9d39e][resolved]]
Feb 17 13:32:39 $host alertmanager[1325]: time=2025-02-17T11:32:39.771Z level=DEBUG source=dispatch.go:530 msg=flushing component=dispatcher $alert alerts=[$alert_name[4c9d39e][resolved]]
``` 

See how there are two flushing messages at the same time, one for each group?

**Comment by grobinson-grafana** [comment]
I am wondering if the two routes have the same Group Key somehow, but cannot see from the logs as it has been redacted.

**Comment by vinfry** [comment]
I have downgraded alertmanager to 0.27, the result is the same:
```
Feb 20 10:49:31 $host alertmanager[3948997]: ts=2025-02-20T08:49:31.600Z caller=notify.go:860 level=debug component=dispatcher receiver=$receiver integration=email[0] aggrGroup="{}/{email_mw=~\"^(?:true)$\"}:{alertname=\"$alert\", email_mw=\"true\", environment=\"$env\", instance=\"$instance\", severity=\"warning\", source=\"promxy\"}" alerts=[$alert[594f0b5][active]] msg="Notify success" attempts=1 duration=30.791608ms
Feb 20 10:49:33 $host alertmanager[3948997]: ts=2025-02-20T08:49:33.036Z caller=notify.go:860 level=debug component=dispatcher receiver=alerta integration=webhook[0] aggrGroup="{}/{}:{alertname=\"$alert\", email_mw=\"true\", environment=\"$env\", instance=\"$instance\", severity=\"warning\", source=\"promxy\"}" alerts=[$alert[594f0b5][active]] msg="Notify success" attempts=1 duration=1.466376604s
Feb 20 10:54:31 $host alertmanager[3948997]: ts=2025-02-20T08:54:31.593Z caller=notify.go:860 level=debug component=dispatcher receiver=$receiver integration=email[0] aggrGroup="{}/{email_mw=~\"^(?:true)$\"}:{alertname=\"$alert\", email_mw=\"true\", environment=\"$env\", instance=\"$instance\", severity=\"warning\", source=\"promxy\"}" alerts=[$alert[594f0b5][resolved]] msg="Notify success" attempts=1 duration=22.725544ms
```
```
alertmanager --version
alertmanager, version 0.27.0 (branch: HEAD, revision: 0aa3c2aad14cff039931923ab16b26b7481783b5)
  build user:       root@22cd11f671e9
  build date:       20240228-11:51:20
  go version:       go1.21.7
  platform:         linux/amd64
  tags:             netgo
```
This is a different alert and has 2 receivers only.

**Comment by grobinson-grafana** [comment]
Just to confirm, are you running a single Alertmanager instance, or are you running Alertmanager in high availability?

**Comment by grobinson-grafana** [comment]
Here is a patch. Do you think you can add it to the current `main` branch, build Alertmanager, and repeat the tests? It should tell us what is happening to those resolved alerts.

```diff
diff --git a/notify/notify.go b/notify/notify.go
index 8fa85c0a..c8e0f68b 100644
--- a/notify/notify.go
+++ b/notify/notify.go
@@ -452,6 +452,8 @@ type RoutingStage map[string]Stage

 // Exec implements the Stage interface.
 func (rs RoutingStage) Exec(ctx context.Context, l *slog.Logger, alerts ...*types.Alert) (context.Context, []*types.Alert, error) {
+	l.Debug("Executing routing stage", "alerts", fmt.Sprintf("%v", alerts))
+
 	receiver, ok := ReceiverName(ctx)
 	if !ok {
 		return ctx, nil, errors.New("receiver missing")
@@ -470,6 +472,8 @@ type MultiStage []Stage

 // Exec implements the Stage interface.
 func (ms MultiStage) Exec(ctx context.Context, l *slog.Logger, alerts ...*types.Alert) (context.Context, []*types.Alert, error) {
+	l.Debug("Executing multi stage", "alerts", fmt.Sprintf("%v", alerts))
+
 	var err error
 	for _, s := range ms {
 		if len(alerts) == 0 {
@@ -490,6 +494,8 @@ type FanoutStage []Stage
 // Exec attempts to execute all stages concurrently and discards the results.
 // It returns its input alerts and a types.MultiError if one or more stages fail.
 func (fs FanoutStage) Exec(ctx context.Context, l *slog.Logger, alerts ...*types.Alert) (context.Context, []*types.Alert, error) {
+	l.Debug("Executing fanout stage", "alerts", fmt.Sprintf("%v", alerts))
+
 	var (
 		wg sync.WaitGroup
 		me types.MultiError
@@ -551,6 +557,8 @@ func NewMuteStage(m types.Muter, metrics *Metrics) *MuteStage {

 // Exec implements the Stage interface.
 func (n *MuteStage) Exec(ctx context.Context, logger *slog.Logger, alerts ...*types.Alert) (context.Context, []*types.Alert, error) {
+	logger.Debug("Executing mute stage", "alerts", fmt.Sprintf("%v", alerts))
+
 	var (
 		filtered []*types.Alert
 		muted    []*types.Alert
@@ -596,7 +604,8 @@ func NewWaitStage(wait func() time.Duration) *WaitStage {
 }

 // Exec implements the Stage interface.
-func (ws *WaitStage) Exec(ctx context.Context, _ *slog.Logger, alerts ...*types.Alert) (context.Context, []*types.Alert, error) {
+func (ws *WaitStage) Exec(ctx context.Context, l *slog.Logger, alerts ...*types.Alert) (context.Context, []*types.Alert, error) {
+	l.Debug("Executing wait stage", "alerts", fmt.Sprintf("%v", alerts))
 	select {
 	case <-time.After(ws.wait()):
 	case <-ctx.Done():
@@ -697,7 +706,8 @@ func (n *DedupStage) needsUpdate(entry *nflogpb.Entry, firing, resolved map[uint
 }

 // Exec implements the Stage interface.
-func (n *DedupStage) Exec(ctx context.Context, _ *slog.Logger, alerts ...*types.Alert) (context.Context, []*types.Alert, error) {
+func (n *DedupStage) Exec(ctx context.Context, l *slog.Logger, alerts ...*types.Alert) (context.Context, []*types.Alert, error) {
+	l.Debug("Executing dedup stage", "alerts", fmt.Sprintf("%v", alerts))
 	gkey, ok := GroupKey(ctx)
 	if !ok {
 		return ctx, nil, errors.New("group key missing")
@@ -745,6 +755,7 @@ func (n *DedupStage) Exec(ctx context.Context, _ *slog.Logger, alerts ...*types.
 	if n.needsUpdate(entry, firingSet, resolvedSet, repeatInterval) {
 		return ctx, alerts, nil
 	}
+	l.Debug("Notifications will not be sent for alerts, no changes", "alerts", fmt.Sprintf("%v", alerts))
 	return ctx, nil, nil
 }

@@ -774,6 +785,8 @@ func NewRetryStage(i Integration, groupName string, metrics *Metrics) *RetryStag
 }

 func (r RetryStage) Exec(ctx context.Context, l *slog.Logger, alerts ...*types.Alert) (context.Context, []*types.Alert, error) {
+	l.Debug("Executing retry stage", "alerts", fmt.Sprintf("%v", alerts))
+
 	r.metrics.numNotifications.WithLabelValues(r.labelValues...).Inc()
 	ctx, alerts, err := r.exec(ctx, l, alerts...)

@@ -914,6 +927,8 @@ func NewSetNotifiesStage(l NotificationLog, recv *nflogpb.Receiver) *SetNotifies

 // Exec implements the Stage interface.
 func (n SetNotifiesStage) Exec(ctx context.Context, l *slog.Logger, alerts ...*types.Alert) (context.Context, []*types.Alert, error) {
+	l.Debug("Executing set notifies stage", "alerts", fmt.Sprintf("%v", alerts))
+
 	gkey, ok := GroupKey(ctx)
 	if !ok {
 		return ctx, nil, errors.New("group key missing")
@@ -953,6 +968,8 @@ func NewTimeMuteStage(muter types.TimeMuter, marker types.GroupMarker, metrics *
 // Exec implements the stage interface for TimeMuteStage.
 // TimeMuteStage is responsible for muting alerts whose route is not in an active time.
 func (tms TimeMuteStage) Exec(ctx context.Context, l *slog.Logger, alerts ...*types.Alert) (context.Context, []*types.Alert, error) {
+	l.Debug("Executing time mute stage", "alerts", fmt.Sprintf("%v", alerts))
+
 	routeID, ok := RouteID(ctx)
 	if !ok {
 		return ctx, nil, errors.New("route ID missing")
@@ -1003,6 +1020,8 @@ func NewTimeActiveStage(muter types.TimeMuter, marker types.GroupMarker, metrics
 // Exec implements the stage interface for TimeActiveStage.
 // TimeActiveStage is responsible for muting alerts whose route is not in an active time.
 func (tas TimeActiveStage) Exec(ctx context.Context, l *slog.Logger, alerts ...*types.Alert) (context.Context, []*types.Alert, error) {
+	l.Debug("Executing time active stage", "alerts", fmt.Sprintf("%v", alerts))
+
 	routeID, ok := RouteID(ctx)
 	if !ok {
 		return ctx, nil, errors.New("route ID missing")
```

**Comment by vinfry** [comment]
> Just to confirm, are you running a single Alertmanager instance, or are you running Alertmanager in high availability?

yes, we have HA, the second server acts as "standby" but I always check its logs as well.



> Here is a patch. Do you think you can add it to the `v0.28.0` tag, build Alertmanager, and repeat the tests? It should tell us what is happening to those resolved alerts.
> 
> diff --git a/notify/notify.go b/notify/notify.go
> index 8fa85c0a..c8e0f68b 100644
> --- a/notify/notify.go
> +++ b/notify/notify.go
> @@ -452,6 +452,8 @@ type RoutingStage map[string]Stage
> 
>  // Exec implements the Stage interface.
>  func (rs RoutingStage) Exec(ctx context.Context, l *slog.Logger, alerts ...*types.Alert) (context.Context, []*types.Alert, error) {
> +	l.Debug("Executing routing stage", "alerts", fmt.Sprintf("%v", alerts))
> +
>  	receiver, ok := ReceiverName(ctx)
>  	if !ok {
>  		return ctx, nil, errors.New("receiver missing")
> @@ -470,6 +472,8 @@ type MultiStage []Stage
> 
>  // Exec implements the Stage interface.
>  func (ms MultiStage) Exec(ctx context.Context, l *slog.Logger, alerts ...*types.Alert) (context.Context, []*types.Alert, error) {
> +	l.Debug("Executing multi stage", "alerts", fmt.Sprintf("%v", alerts))
> +
>  	var err error
>  	for _, s := range ms {
>  		if len(alerts) == 0 {
> @@ -490,6 +494,8 @@ type FanoutStage []Stage
>  // Exec attempts to execute all stages concurrently and discards the results.
>  // It returns its input alerts and a types.MultiError if one or more stages fail.
>  func (fs FanoutStage) Exec(ctx context.Context, l *slog.Logger, alerts ...*types.Alert) (context.Context, []*types.Alert, error) {
> +	l.Debug("Executing fanout stage", "alerts", fmt.Sprintf("%v", alerts))
> +
>  	var (
>  		wg sync.WaitGroup
>  		me types.MultiError
> @@ -551,6 +557,8 @@ func NewMuteStage(m types.Muter, metrics *Metrics) *MuteStage {
> 
>  // Exec implements the Stage interface.
>  func (n *MuteStage) Exec(ctx context.Context, logger *slog.Logger, alerts ...*types.Alert) (context.Context, []*types.Alert, error) {
> +	logger.Debug("Executing mute stage", "alerts", fmt.Sprintf("%v", alerts))
> +
>  	var (
>  		filtered []*types.Alert
>  		muted    []*types.Alert
> @@ -596,7 +604,8 @@ func NewWaitStage(wait func() time.Duration) *WaitStage {
>  }
> 
>  // Exec implements the Stage interface.
> -func (ws *WaitStage) Exec(ctx context.Context, _ *slog.Logger, alerts ...*types.Alert) (context.Context, []*types.Alert, error) {
> +func (ws *WaitStage) Exec(ctx context.Context, l *slog.Logger, alerts ...*types.Alert) (context.Context, []*types.Alert, error) {
> +	l.Debug("Executing wait stage", "alerts", fmt.Sprintf("%v", alerts))
>  	select {
>  	case <-time.After(ws.wait()):
>  	case <-ctx.Done():
> @@ -697,7 +706,8 @@ func (n *DedupStage) needsUpdate(entry *nflogpb.Entry, firing, resolved map[uint
>  }
> 
>  // Exec implements the Stage interface.
> -func (n *DedupStage) Exec(ctx context.Context, _ *slog.Logger, alerts ...*types.Alert) (context.Context, []*types.Alert, error) {
> +func (n *DedupStage) Exec(ctx context.Context, l *slog.Logger, alerts ...*types.Alert) (context.Context, []*types.Alert, error) {
> +	l.Debug("Executing dedup stage", "alerts", fmt.Sprintf("%v", alerts))
>  	gkey, ok := GroupKey(ctx)
>  	if !ok {
>  		return ctx, nil, errors.New("group key missing")
> @@ -745,6 +755,7 @@ func (n *DedupStage) Exec(ctx context.Context, _ *slog.Logger, alerts ...*types.
>  	if n.needsUpdate(entry, firingSet, resolvedSet, repeatInterval) {
>  		return ctx, alerts, nil
>  	}
> +	l.Debug("Notifications will not be sent for alerts, no changes", "alerts", fmt.Sprintf("%v", alerts))
>  	return ctx, nil, nil
>  }
> 
> @@ -774,6 +785,8 @@ func NewRetryStage(i Integration, groupName string, metrics *Metrics) *RetryStag
>  }
> 
>  func (r RetryStage) Exec(ctx context.Context, l *slog.Logger, alerts ...*types.Alert) (context.Context, []*types.Alert, error) {
> +	l.Debug("Executing retry stage", "alerts", fmt.Sprintf("%v", alerts))
> +
>  	r.metrics.numNotifications.WithLabelValues(r.labelValues...).Inc()
>  	ctx, alerts, err := r.exec(ctx, l, alerts...)
> 
> @@ -914,6 +927,8 @@ func NewSetNotifiesStage(l NotificationLog, recv *nflogpb.Receiver) *SetNotifies
> 
>  // Exec implements the Stage interface.
>  func (n SetNotifiesStage) Exec(ctx context.Context, l *slog.Logger, alerts ...*types.Alert) (context.Context, []*types.Alert, error) {
> +	l.Debug("Executing set notifies stage", "alerts", fmt.Sprintf("%v", alerts))
> +
>  	gkey, ok := GroupKey(ctx)
>  	if !ok {
>  		return ctx, nil, errors.New("group key missing")
> @@ -953,6 +968,8 @@ func NewTimeMuteStage(muter types.TimeMuter, marker types.GroupMarker, metrics *
>  // Exec implements the stage interface for TimeMuteStage.
>  // TimeMuteStage is responsible for muting alerts whose route is not in an active time.
>  func (tms TimeMuteStage) Exec(ctx context.Context, l *slog.Logger, alerts ...*types.Alert) (context.Context, []*types.Alert, error) {
> +	l.Debug("Executing time mute stage", "alerts", fmt.Sprintf("%v", alerts))
> +
>  	routeID, ok := RouteID(ctx)
>  	if !ok {
>  		return ctx, nil, errors.New("route ID missing")
> @@ -1003,6 +1020,8 @@ func NewTimeActiveStage(muter types.TimeMuter, marker types.GroupMarker, metrics
>  // Exec implements the stage interface for TimeActiveStage.
>  // TimeActiveStage is responsible for muting alerts whose route is not in an active time.
>  func (tas TimeActiveStage) Exec(ctx context.Context, l *slog.Logger, alerts ...*types.Alert) (context.Context, []*types.Alert, error) {
> +	l.Debug("Executing time active stage", "alerts", fmt.Sprintf("%v", alerts))
> +
>  	routeID, ok := RouteID(ctx)
>  	if !ok {
>  		return ctx, nil, errors.New("route ID missing")

Could you build a new tag with those changes included? Unfortunately due to our company policy, we cannot build from sources.

BTW, I have used an old tag 0.23 in our environment and it works without any problems, I see no stuck alerts in alerta, and all "resolve" messages are being sent without any issues.

**Comment by grobinson-grafana** [comment]
I can't I'm afraid, I'm not an official maintainer. I tried reproducing the issue on 0.28 but was unsuccessful too.

**Comment by grobinson-grafana** [comment]
If you cannot build from source, it might be worth stepping through each release (`0.23` `0.24` etc) until you find the release where this stops working. We can then look at the diff between those two releases and see if there is something wrong.

**Comment by grobinson-grafana** [comment]
Can I assume the problem is no longer occurring/you found the cause of the issue? Did you have any luck finding which version this stopped working?

**Comment by vinfry** [comment]
Unfortunately, I haven't found the problem yet and cannot test your changes. I hope the new version with extended logging will be released soon.

**Comment by ccolvin-ebay** [comment]
Does anyone know if there's any updates on addressing this issue?  I'm currently running into this as well.  Was pulling my hair out thinking I was just dealing with intermittent network issues that I couldn't capture.

**Comment by ccolvin-ebay** [comment]
After walking back versions, 0.26.0 seems to not have the issue, so it does seem like the problem was introduced in 0.27.0.  I'll update here again if we run into it on 0.26.0.

I did see that there was a new release recently, but none of the noted changes seem to address this problem.

**Comment by TheMeier** [comment]
There has been no activity on this issue for a long time. In the meantime a lot of code has changed in Alertmanager. Therefore I assume that the original request is either not relevant anymore or has been addressed in some other way.

If I am wrong please re-open this issue or open a new one.

**Comment by ccolvin-ebay** [comment]
@TheMeier that does not sound like a good reason to close an issue.  Why not ask anyone to test before closing?  Was there any specific change to how webhook notifications are handled that should impact this?  The commit history does not seem to suggest such:
https://github.com/prometheus/alertmanager/commits/main/notify/webhook

Why guess or assume?

**Comment by ccolvin-ebay** [comment]
I did what was asked last year on this issue, walked back versions, and reported back that the issue seems to have surfaced with 0.27.0.  Never heard back afterward.  While the OP is MIA, this is a real issue.  Is it appropriate to close this issue without specifically addressing it, or at least confirming it has been resolved first?

We are still using 0.26.0 and have been waiting for a fix.

**Comment by TheMeier** [comment]
Hi @ccolvin-ebay,

thank you for your feedback

can you please validate that this issue still is present with the latest version (0.31.1) **AND** it is not because of very short `group_wait`/`group_interval` settings. (e.g. less then 1m)

**Comment by ccolvin-ebay** [comment]
Thanks for hearing me out, @TheMeier.  I will today if I can fit it in, but tomorrow at the latest.

**Comment by ccolvin-ebay** [comment]
@TheMeier, testing now, but the issue was intermittent, around 30%-50% of the time.  Getting through enough tests to feel comfortable the issue is cleared will take a bit, so this will likely bleed into tomorrow.

That said, I'm curious about the mention of group_wait and group_interval settings.  I know the OP had low settings in there, but we have been running 0.26.0 with a group_wait of 30s since last year without issue.  Our group_interval is 1m.  Should I expect these settings to be too short with newer versions for some reason?

**Comment by ccolvin-ebay** [comment]
25 back-to-back, with no missed resolution notifications, all with group_wait = 30s and group_interval = 1m.  I don't think I ever had a streak like that with 0.27.0 or 0.28.0.  I'm going to test more, still.  But this is definitely improved from before.  I don't see a need to keep this open further.  Thank you for humoring me.  Definitely better to know for sure.

I'll report back if something changes in my continued testing.

**Comment by TheMeier** [comment]
@ccolvin-ebay Thank you for testing this and donating your time.

I mentioned the low intervals because in HA setups low intervals can cause issues https://prometheus.io/docs/alerting/latest/high_availability/#common-pitfalls (2. Not waiting for gossip to settle) There is a minimum time gossip needs to be stable. This has been discussed in multiple issues.


So I will close this now, we can always re-open it or raise a new isssu if needed.
