### ISSUE TITLE
Visualization fails to execute match_re correctly

### ISSUE THREAD

**Issue by iksaif** [prometheus/alertmanager#626]
lib/routing-tree.js doesn't seem to handle match_re properly. I defined a set of routes, and the route with match_re always seem to match everything.

My rule looks like "severity = page|interrupts" but will match alerts that don't even have a severity

When I hover the node, the text is "severity=/[object Object]/"

**Comment by iksaif** [comment]
Going to api/v1/status I get:
```json
"match_re": {
"severity": {}
}
```

That would explain things

**Comment by iksaif** [comment]
I guess regex objects are not being marshalled properly in json.

**Comment by bspradling8** [comment]
I'm running into this same issue. Did you find a workaround?

**Comment by stuartnelson3** [comment]
What version are you using? Seems this was fixed in january: https://github.com/prometheus/alertmanager/commit/f2ba86e9d204fbc08dca34940a353d61f7564987

We haven't had a release since then, unfortunately, but if you build from master it should be fine.

**Comment by bspradling8** [comment]
Interesting, I checked to see that I'm running the latest, the docker container is `prom/alertmanager:v0.5.1`. 

My routes are here: 

>   routes:
  - match_re:
       job: dev
    receiver: {team}-dev-receiver

All the online helpers with tree routing seem to get this right when I copy my configuration in, it is just when the `alertmanager` is actually running, I never see my `{team}-dev-receiver` matching. 

I also went here `/api/v1/status` and saw the same thing: 

> "match_re": {
       "job": {}
    }

**Comment by stuartnelson3** [comment]
Yeah, 0.5.1 was released before this fix. You'll have to build from a later SHA to get the fix.

**Comment by MrAlias** [comment]
@stuartnelson3 it looks like the [above mentioned PR](https://github.com/prometheus/alertmanager/commit/f2ba86e9d204fbc08dca34940a353d61f7564987) was merged into the v0.6 release as well as master, but I'm still experiencing routing visualization issues when using those releases.

I'm using alertmanager (version=0.6.1, branch=release-0.6, revision=5aeaf2cb988b0094b7998bbe6568bba23a0eb9c2) and the following test config:

```
route:
  receiver: ops-nag
  routes:
  - match_re:
      service: apache|nginx
      severity: page
    receiver: web-page
  - match_re:
      service: apache|nginx
    receiver: web-nag
  - match:
      severity: page
    receiver: ops-page
receivers:
- name: ops-nag
- name: ops-page
- name: web-nag
- name: web-page
```

When I use a label set of `{service="hbase"}` I would expect the page to go to `ops-nag` (the parent default), but the visualization tool shows it going to `web-page`:

![error-on-v0 6](https://cloud.githubusercontent.com/assets/5543599/25686626/b029d5fe-3024-11e7-9bff-f80fc3eb257c.png)

and a more detailed view of the routing with the mouse over error:

![close-up-error-on-v0 6](https://cloud.githubusercontent.com/assets/5543599/25686708/3b28f7e8-3025-11e7-9587-972d5d1f79c8.png)

FWIW I also tried this on the current master as well (version=0.6.1, branch=master, revision=8566c9531b1107bc243d3cba7173406e39f7771d) and had the same result.  I also tried this with a variety of other label sets with similarly incorrect and confusing results (e.g. `{service="lol"}` goes to `web-page` not `ops-nag`, but `{service="asdf"}` as expected goes to `ops-nag` ¯\_(ツ)_/¯).

I have verified that the underlying system is routing as I would expect the pages to be sent, so like the other people having this issue it doesn't seem to be from the underlying matching.  Given this it seems to be the same behavior as described above, so I'm not sure the issue has been resolved.

**Comment by snarlysodboxer** [comment]
I'm having this exact same problem in v0.6.1.

**Comment by MrAlias** [comment]
It looks like [this](https://github.com/prometheus/alertmanager/commit/6aece86ac15427faae5efe6ed651d1a8e5b7cf77) resolved this issue for me.

FWIW it also looks like this change was [merged into release-0.6](https://github.com/prometheus/alertmanager/pull/777) (which is also working now).

**Comment by mxinden** [comment]
@iksaif according to @MrAlias this is fixed. Feel free to reopen if this is still an issue on any 0.6 versions. I hope we will get the routing tree back into the new UI soon.
